"""Request and content models for the multi-agent research report.

A report is shared by every user who views it, so nothing here is
user-specific: no portfolio, no user id, and times are in market time.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.models.chat import Citation, PriceChart
from app.models.rag import Ticker

AgentName = Literal["transcripts", "market", "writer"]
SectionKey = Literal["summary", "drivers", "guidance", "changes", "stock", "risks"]

# Report sections, in display order.
SECTIONS: tuple[tuple[SectionKey, str], ...] = (
    ("summary", "Summary"),
    ("drivers", "Demand and business drivers"),
    ("guidance", "Guidance and outlook"),
    ("changes", "What changed vs last quarter"),
    ("stock", "Stock performance"),
    ("risks", "Risks"),
)

DISCLAIMER = (
    "This report is generated by AI from earnings call transcripts and market "
    "data. It is general information, not financial advice."
)


class ReportRequest(BaseModel):
    """Generate one ticker's report. Only the API gateway may send this.

    ``user_id`` (from the gateway's verified JWT) is used for tracing (hashed)
    and never stored in the report.
    """

    user_id: str = Field(min_length=1, max_length=64)
    is_anonymous: bool = False
    ticker: Ticker
    # A report for the same quarter newer than this is kept (0 = always regenerate).
    regenerate_after_days: int = Field(default=7, ge=0, le=365)


class ReportDraft(BaseModel):
    """The writer's structured output: one Markdown string per section."""

    summary: str = Field(
        description="3-5 sentences: the most important points of the report."
    )
    drivers: str = Field(description="Demand and business drivers, as bullets.")
    guidance: str = Field(description="Guidance and outlook, as bullets.")
    changes: str = Field(
        description="What changed vs the previous quarter, under the comparison "
        "headings."
    )
    stock: str = Field(description="Stock performance from the market data only.")
    risks: str = Field(description="Risks and headwinds, as bullets.")


class ReportSection(BaseModel):
    key: SectionKey
    title: str
    markdown: str


class ReportPeriod(BaseModel):
    fiscal_year: int
    fiscal_quarter: int = Field(ge=1, le=4)
    call_date: str | None = None


class DataSource(BaseModel):
    """A market-data tool result the report cites as [D1], [D2], ..."""

    id: str = Field(pattern=r"^D\d{1,2}$")
    kind: Literal["quote", "price_history"]
    ticker: str
    label: str
    as_of: str | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class AgentRun(BaseModel):
    """How one agent's step went (also traced as a span in Langfuse)."""

    agent: AgentName
    model: str
    status: Literal["ok", "failed"]
    input_tokens: int = 0
    output_tokens: int = 0
    cost_usd: float = 0.0
    latency_ms: float = 0.0
    model_calls: int = 0
    tool_calls: int = 0


class ReportAsOf(BaseModel):
    """What the report's data is current to (market time for quotes)."""

    latest_call: str | None = None
    quote: str | None = None
    prices: str | None = None


class ResearchReportContent(BaseModel):
    """What is stored in ``research_reports.content`` and shown to users."""

    version: Literal[1] = 1
    ticker: str
    company_name: str
    quarter: ReportPeriod
    prior_quarter: ReportPeriod | None = None
    sections: list[ReportSection]
    citations: list[Citation] = Field(default_factory=list)
    data_sources: list[DataSource] = Field(default_factory=list)
    chart: PriceChart | None = None
    market_data_available: bool = True
    # False when the latest call had no comparable earlier call.
    comparison_available: bool = True
    as_of: ReportAsOf = Field(default_factory=ReportAsOf)
    disclaimer: str = DISCLAIMER
    agents: list[AgentRun] = Field(default_factory=list)

    def section(self, key: SectionKey) -> ReportSection | None:
        return next((s for s in self.sections if s.key == key), None)
