import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";

// The header's status dot polls /api/health; not under test here.
vi.mock("@/components/HealthIndicator", () => ({ HealthIndicator: () => null }));
vi.mock("@/context/auth-context", () => ({ useAuth: vi.fn() }));
vi.mock("@/lib/reportsApi", () => ({
  listReports: vi.fn(),
  getReport: vi.fn(),
  streamReport: vi.fn(),
}));

import { useAuth } from "@/context/auth-context";
import { ApiError } from "@/lib/api";
import type { Citation, PriceChart } from "@/lib/chatApi";
import * as reportsApi from "@/lib/reportsApi";
import type {
  Report,
  ReportStreamEvent,
  ReportSummary,
  ReportView,
} from "@/lib/reportsApi";
import { GENERATING_POLL_MS } from "@/hooks/useReports";
import { ReportsPage } from "./ReportsPage";

const api = vi.mocked(reportsApi);

const citation: Citation = {
  id: 1,
  ticker: "NVDA",
  companyName: "Nvidia Corp",
  fiscalYear: 2027,
  fiscalQuarter: 2,
  callDate: "2026-08-26",
  speaker: "Colette Kress",
  role: "CFO",
  section: "prepared_remarks",
  text: "Data center revenue was a record.",
};

const chart: PriceChart = {
  id: "report-price-chart",
  kind: "price_history",
  ticker: "NVDA",
  period: "6mo",
  currency: "USD",
  points: [
    { date: "2026-04-06", close: 150 },
    { date: "2026-10-06", close: 180 },
  ],
  firstClose: 150,
  lastClose: 180,
  change: 30,
  changePercent: 20,
  high: 182,
  low: 140,
  asOf: null,
};

const Q2 = { fiscalYear: 2027, fiscalQuarter: 2, label: "Q2 FY2027" };

function report(overrides: Partial<Report> = {}): Report {
  return {
    ticker: "NVDA",
    companyName: "Nvidia Corp",
    quarter: { ...Q2, callDate: "2026-08-26" },
    priorQuarter: {
      fiscalYear: 2027,
      fiscalQuarter: 1,
      label: "Q1 FY2027",
      callDate: null,
    },
    sections: [
      { key: "summary", title: "Summary", markdown: "Demand led the quarter [1]." },
      {
        key: "drivers",
        title: "Demand and business drivers",
        markdown: "- Data center [1].",
      },
      { key: "guidance", title: "Guidance and outlook", markdown: "- Guided up [1]." },
      {
        key: "changes",
        title: "What changed vs last quarter",
        markdown: "### New\n- X [1].",
      },
      {
        key: "stock",
        title: "Stock performance",
        markdown: "- Up 20% over 6 months [D2].",
      },
      { key: "risks", title: "Risks", markdown: "- Supply [1]." },
    ],
    citations: [citation],
    dataSources: [
      {
        id: "D2",
        kind: "price_history",
        ticker: "NVDA",
        label: "NVDA price history, 6mo (2026-04-06 to 2026-10-06)",
        asOf: "2026-10-06",
        data: {
          change_percent: 20,
          high: 182,
          high_date: "2026-09-30",
          currency: "USD",
        },
      },
    ],
    chart: null,
    marketDataAvailable: true,
    comparisonAvailable: true,
    asOf: {
      latestCall: "2026-08-26",
      quote: "2026-10-06 4:00 PM EDT",
      prices: "2026-10-06",
    },
    disclaimer: "Generated by AI. General information, not financial advice.",
    generatedAt: "2026-10-07T12:00:00.000Z",
    ...overrides,
  };
}

function view(overrides: Partial<ReportView> = {}): ReportView {
  return {
    ticker: "NVDA",
    companyName: "Nvidia Corp",
    latestQuarter: Q2,
    report: report(),
    outdated: false,
    generating: false,
    canGenerate: true,
    blockedReason: null,
    regenerateAvailableAt: null,
    usage: {
      used: 0,
      limit: 2,
      remaining: 2,
      resetsAt: "2026-10-08T00:00:00.000Z",
      isDemo: false,
    },
    ...overrides,
  };
}

const summaries: ReportSummary[] = [
  {
    ticker: "AAPL",
    companyName: "Apple Inc.",
    latestQuarter: { fiscalYear: 2026, fiscalQuarter: 3, label: "Q3 FY2026" },
    report: null,
    generating: false,
  },
  {
    ticker: "NVDA",
    companyName: "Nvidia Corp",
    latestQuarter: Q2,
    report: { generatedAt: "2026-10-07T12:00:00.000Z", quarter: Q2, outdated: false },
    generating: false,
  },
];

function renderAt(path: string, { isDemo = false } = {}) {
  vi.mocked(useAuth).mockReturnValue({
    isDemo,
    user: isDemo ? null : { email: "a@example.com" },
    signOut: vi.fn(),
  } as never);
  return render(
    <MemoryRouter initialEntries={[path]}>
      <Routes>
        <Route path="/reports/:ticker?" element={<ReportsPage />} />
      </Routes>
    </MemoryRouter>,
  );
}

beforeAll(async () => {
  // Load the lazy Recharts chunk up front (see ChatCharts.test.tsx).
  await import("@/components/chat/charts/ChartView");
}, 60_000);

beforeEach(() => {
  vi.clearAllMocks();
  api.listReports.mockResolvedValue({ tickers: summaries, usage: view().usage });
  api.getReport.mockResolvedValue(view());
});

describe("ReportsPage", () => {
  it("lists companies with their report status and opens the chosen one", async () => {
    renderAt("/reports");

    const picker = await screen.findByLabelText("Company");
    const options = within(picker)
      .getAllByRole("option")
      .map((o) => o.textContent);
    expect(options).toEqual([
      "Choose a company",
      "AAPL · Apple Inc. (no report yet)",
      "NVDA · Nvidia Corp (report ready)",
    ]);
    expect(
      screen.getByText("Choose a company to read its report."),
    ).toBeInTheDocument();

    fireEvent.change(picker, { target: { value: "NVDA" } });

    expect(
      await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" }),
    ).toBeVisible();
    expect(api.getReport).toHaveBeenCalledWith("NVDA");
  });

  it("shows the report with its dates, six sections and the disclaimer", async () => {
    renderAt("/reports/nvda");

    await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" });
    expect(
      screen.getByText(
        "Based on the Q2 FY2027 earnings call (Aug 26, 2026), compared with Q1 FY2027.",
      ),
    ).toBeInTheDocument();
    expect(screen.getByText("Generated on Oct 7, 2026")).toBeInTheDocument();
    expect(screen.getByText(/Earnings call Aug 26, 2026/)).toBeInTheDocument();
    expect(screen.getByText(/Quote as of 2026-10-06 4:00 PM EDT/)).toBeInTheDocument();
    expect(screen.getByText(/Prices through Oct 6, 2026/)).toBeInTheDocument();
    expect(
      screen.getAllByRole("heading", { level: 3 }).map((h) => h.textContent),
    ).toEqual([
      "Summary",
      "Demand and business drivers",
      "Guidance and outlook",
      "What changed vs last quarter",
      "Stock performance",
      "Risks",
    ]);
    // The comparison's own headings sit below the section title.
    expect(screen.getByRole("heading", { level: 4, name: "New" })).toBeVisible();
    expect(screen.getByText(/not financial advice/)).toBeInTheDocument();
    expect(api.getReport).toHaveBeenCalledWith("NVDA");
  });

  it("opens the cited passage and the cited market data", async () => {
    renderAt("/reports/NVDA");

    const summary = await screen.findByText(/Demand led the quarter/);
    fireEvent.click(within(summary).getByRole("button", { name: /Source 1/ }));
    expect(await screen.findByText("Data center revenue was a record.")).toBeVisible();
    fireEvent.keyDown(document.activeElement ?? document.body, { key: "Escape" });

    const stock = screen.getByText(/Up 20% over 6 months/);
    fireEvent.click(within(stock).getByRole("button", { name: /Market data D2/ }));
    const dialog = await screen.findByRole("dialog");
    expect(within(dialog).getByText(/NVDA price history, 6mo/)).toBeVisible();
    expect(within(dialog).getByText("20.00%")).toBeVisible();
    expect(within(dialog).getByText("Sep 30, 2026")).toBeVisible();
  });

  it("draws the price chart in the stock performance section", async () => {
    api.getReport.mockResolvedValue(view({ report: report({ chart }) }));
    renderAt("/reports/NVDA");

    const caption = await screen.findByText("NVDA · 6 months");
    const section = screen
      .getByRole("heading", { name: "Stock performance" })
      .closest(".rounded-xl") as HTMLElement;
    expect(section).toContainElement(caption);
  });

  it("streams per-agent progress while generating, then shows the report", async () => {
    api.getReport.mockResolvedValueOnce(view({ report: null }));
    let emit: (event: ReportStreamEvent) => void = () => {};
    let finish: () => void = () => {};
    api.streamReport.mockImplementation((_ticker, onEvent) => {
      emit = onEvent;
      return new Promise<void>((resolve) => {
        finish = resolve;
      });
    });
    renderAt("/reports/NVDA");

    expect(
      await screen.findByText("There's no report for Nvidia Corp (Q2 FY2027) yet."),
    ).toBeVisible();
    fireEvent.click(screen.getByRole("button", { name: /Generate report/ }));

    const progress = await screen.findByRole("list", { name: "Report progress" });
    expect(
      within(progress)
        .getAllByRole("listitem")
        .map((li) => li.textContent),
    ).toEqual([
      "Researching transcripts… (pending)",
      "Analyzing price data… (pending)",
      "Writing report… (pending)",
    ]);
    emit({
      type: "agent",
      agent: "transcripts",
      state: "running",
      label: "Researching transcripts…",
    });
    emit({
      type: "agent",
      agent: "market",
      state: "running",
      label: "Analyzing price data…",
    });
    emit({
      type: "agent",
      agent: "market",
      state: "done",
      label: "Analyzing price data…",
      summary: "2 data sources",
    });
    await waitFor(() =>
      expect(
        within(progress)
          .getAllByRole("listitem")
          .map((li) => li.textContent),
      ).toEqual([
        "Researching transcripts… (running)",
        "Analyzing price data… · 2 data sources (done)",
        "Writing report… (pending)",
      ]),
    );
    expect(screen.getByRole("button", { name: /Generating…/ })).toBeDisabled();
    expect(
      screen.getByText(
        "Takes about a minute. You can leave this page; the report will be ready when you return.",
      ),
    ).toBeVisible();
    expect(screen.getByLabelText("Company")).toBeDisabled();

    emit({ type: "done", report: report() });
    finish();

    expect(
      await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" }),
    ).toBeVisible();
    await waitFor(() => expect(api.getReport).toHaveBeenCalledTimes(2)); // fresh permissions
    expect(api.listReports).toHaveBeenCalledTimes(2);
  });

  it("shows a failed generation and which agent failed", async () => {
    api.getReport.mockResolvedValue(view({ report: null }));
    api.streamReport.mockImplementation(async (_ticker, onEvent) => {
      onEvent({
        type: "agent",
        agent: "transcripts",
        state: "running",
        label: "Researching transcripts…",
      });
      onEvent({
        type: "error",
        code: "research_failed",
        message: "The transcript research found no citable passages.",
        retryable: true,
      });
    });
    renderAt("/reports/NVDA");

    fireEvent.click(await screen.findByRole("button", { name: /Generate report/ }));

    expect(await screen.findByRole("alert")).toHaveTextContent(
      "The transcript research found no citable passages.",
    );
  });

  it("explains a refusal before streaming (e.g. the daily cap)", async () => {
    api.streamReport.mockRejectedValue(
      new ApiError(429, "You can generate 2 reports a day.", "report_limit_reached"),
    );
    api.getReport.mockResolvedValue(view({ report: null }));
    renderAt("/reports/NVDA");

    fireEvent.click(await screen.findByRole("button", { name: /Generate report/ }));

    expect(await screen.findByRole("alert")).toHaveTextContent(
      "You can generate 2 reports a day.",
    );
  });

  it("is view-only for demo users", async () => {
    api.getReport.mockResolvedValue(
      view({ canGenerate: false, blockedReason: "demo" }),
    );
    renderAt("/reports/NVDA", { isDemo: true });

    await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" });
    expect(screen.queryByRole("button", { name: /generate/i })).not.toBeInTheDocument();
    expect(
      screen.getByText("Demo accounts can view reports. Sign up to generate one."),
    ).toBeVisible();
  });

  it.each([
    [
      "fresh",
      { regenerateAvailableAt: "2026-10-12T12:00:00.000Z" },
      /regenerate it on Oct 12, 2026/,
    ],
    ["daily_limit", {}, /generated today's 2 reports\. More /],
    ["global_limit", {}, /reached its daily capacity/],
    ["in_progress", {}, /being generated/],
  ] as const)("disables regenerating when %s", async (reason, extra, text) => {
    api.getReport.mockResolvedValue(
      view({ canGenerate: false, blockedReason: reason, ...extra }),
    );
    renderAt("/reports/NVDA");

    const button = await screen.findByRole("button", { name: /Regenerate report/ });
    expect(button).toBeDisabled();
    expect(screen.getByText(text)).toBeVisible();
  });

  it("marks a report for an older quarter and offers an updated one", async () => {
    api.getReport.mockResolvedValue(
      view({
        latestQuarter: { fiscalYear: 2027, fiscalQuarter: 3, label: "Q3 FY2027" },
        outdated: true,
      }),
    );
    renderAt("/reports/NVDA");

    expect(await screen.findByRole("note")).toHaveTextContent(
      "A newer earnings call (Q3 FY2027) is indexed. This report covers Q2 FY2027.",
    );
    expect(screen.getByRole("button", { name: /Generate report/ })).toBeEnabled();
  });

  it("shows when there's no comparison or price data, as the report says", async () => {
    api.getReport.mockResolvedValue(
      view({
        report: report({
          priorQuarter: null,
          comparisonAvailable: false,
          asOf: { latestCall: "2026-08-26", quote: null, prices: null },
        }),
      }),
    );
    renderAt("/reports/NVDA");

    expect(
      await screen.findByText("Based on the Q2 FY2027 earnings call (Aug 26, 2026)."),
    ).toBeVisible();
    expect(screen.queryByText(/Quote as of/)).not.toBeInTheDocument();
  });
});

describe("ReportsPage status refresh", () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it("polls while a report is generating until it's ready", async () => {
    vi.useFakeTimers({ shouldAdvanceTime: true });
    const generating = summaries.map((s) =>
      s.ticker === "NVDA" ? { ...s, report: null, generating: true } : s,
    );
    api.listReports.mockResolvedValueOnce({ tickers: generating, usage: view().usage });
    api.getReport.mockResolvedValueOnce(view({ report: null, generating: true }));
    renderAt("/reports/NVDA");

    expect(
      await screen.findByText("Nvidia Corp's report is being generated."),
    ).toBeVisible();
    const picker = screen.getByLabelText("Company");
    expect(within(picker).getByRole("option", { name: /NVDA/ })).toHaveTextContent(
      "(generating)",
    );

    // The run finishes (perhaps one the user started before leaving).
    await vi.advanceTimersByTimeAsync(GENERATING_POLL_MS);

    expect(
      await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" }),
    ).toBeVisible();
    expect(within(picker).getByRole("option", { name: /NVDA/ })).toHaveTextContent(
      "(report ready)",
    );
    // Nothing is generating any more: no further polling.
    const calls = api.listReports.mock.calls.length;
    await vi.advanceTimersByTimeAsync(GENERATING_POLL_MS * 3);
    expect(api.listReports).toHaveBeenCalledTimes(calls);
  });

  it("refetches when the user comes back to the tab", async () => {
    renderAt("/reports/NVDA");
    await screen.findByRole("heading", { name: "Nvidia Corp (NVDA)" });
    expect(api.listReports).toHaveBeenCalledTimes(1);

    Object.defineProperty(document, "visibilityState", {
      configurable: true,
      get: () => "visible",
    });
    document.dispatchEvent(new Event("visibilitychange"));

    await waitFor(() => expect(api.listReports).toHaveBeenCalledTimes(2));
    expect(api.getReport).toHaveBeenCalledTimes(2);
  });
});
